[tool.black]
line-length = 120
target-version = ['py37']
extend-exclude = '''
/(
  \.toml
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
force-exclude = '''
/(
   /*.txt
   /docs
   /docs/*
)\
'''
