[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.rst
  |\.md
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |build
  |dist
)/
'''



[tool.ruff]

[tool.ruff.lint]
select = ["F401"] # TODO: eventually, expand to other 'I', 'D', and other 'F' linting
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["I"]  # Must maintain explicit order for imports for check registration
"nwbinspector/__init__.py" = ["F401", "I"]  # Temporarily keeping all exposure for back-compatibility
"inspector_tools/__init__.py" = ["F401", "I"] # Temporarily keeping all exposure for back-compatibility


[tool.codespell]
skip = '.git*,*.pdf,*.css'
check-hidden = true
ignore-words-list = 'assertin'
