[tool.black]
line-length = 120
target-version = ['py39']
extend-exclude = '''
/(
  \.toml
  |\.rst
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |build
  |dist
)/
'''
