name: Daily workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST

jobs:

  run-daily-tests:
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/testing.yml@dev

  run-daily-doc-link-checks:
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/doc-link-checks.yml@dev

  notify:
    runs-on: ubuntu-latest
    needs: [run-daily-tests, run-daily-doc-link-checks]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465  # TSL
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: NWB Inspector Daily Failure
        to: ${{ secrets.DAILY_FAILURE_EMAIL_LIST }}  # add more with commas, no separation
        from: NWB Inspector
        body: "The daily workflow for the NWB Inspector failed: please check status at https://github.com/NeurodataWithoutBorders/nwbinspector/actions/workflows/dailies.yml"
