name: Deploy tests

on:
  pull_request:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  assess-file-changes:
    uses: catalystneuro/neuroconv/.github/workflows/assess-file-changes.yml@main

  detect-changelog-updates:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    name: Auto-detecting CHANGELOG.md updates
    runs-on: ubuntu-latest
    steps:
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'true' }}
        run: echo "CHANGELOG.md has been updated."
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'false' }}
        run: |
          echo "CHANGELOG.md has not been updated."
          0

  run-doc-link-checks:
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/doc-link-checks.yml@dev

  run-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/testing.yml@dev

  run-streaming-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/streaming-tests.yml@dev

  run-past-gallery:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/version-gallery.yml@dev

  run-dev-gallery:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/dev-gallery.yml@dev

  test-dandi-latest:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/dandi-release.yml@dev

  test-dandi-dev:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/dandi-dev.yml@dev

  check-final-status:
    name: All tests passing
    if: always()

    needs:
    - run-tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the all jobs succeeded or at least one failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: run-tests  # Sometimes only docs are adjusted
        jobs: ${{ toJSON(needs) }}
