name: Streaming tests
on: workflow_call

jobs:
  build-and-test:
    name: Streaming tests using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Install pytest
        run: pip install pytest

      - name: Install package
        run: |
          pip install .
          pip install dandi
      - name: Install HDMF-zarr # temporary
        run: pip install hdmf-zarr
      - name: Install latest HDMF # temporary
        run: pip install -U hdmf
      - name: Uninstall h5py
        run: pip uninstall -y h5py
      - name: Install ROS3
        run: conda install -c conda-forge h5py

      - name: Run pytest on stream tests
        run: pytest tests/ -rsx tests/streaming_tests.py
