name: Streaming tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  build-and-test:
    name: Streaming tests using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]  # TODO: update mac and streaming methods
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov

      - name: Install package
        run: pip install ".[dandi]"

      - name: Run pytest on stream tests with coverage
        run: |
          pytest -rsx --cov=nwbinspector --cov-report xml:./api_coverage.xml tests/streaming_tests.py
          pytest -rsx --cov=nwbinspector --cov-report xml:./cli_coverage.xml tests/streaming_cli_tests.py

      - if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./api_coverage.xml

      - if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./cli_coverage.xml
