name: Testing
on: pull_request
jobs:
  build-and-test:
    name: Testing using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.10"]
    steps:
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: Install package
        run: pip install -e .
      - name: Uninstall h5py
        run: pip uninstall -y h5py
      - name: Install ROS3
        run: conda install -c conda-forge h5py
      - name: Run pytest with coverage
        run: pytest --cov=./ --cov-report xml:./nwbinspector/nwbinspector/coverage.xml
      - if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          version: "v0.1.15"
          fail_ci_if_error: true
          file: ./nwbinspector/nwbinspector/coverage.xml
          flags: unittests
