name: Generate and Upload Testing Files
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DANDI_API_KEY:
        required: true

env:
  DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

jobs:
  build-and-test:
    name: Generate and Upload Testing Files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install DANDI
        run: pip install -e .[dandi]
      - name: Install older PyNWB version to generate example invalid files
        run: |
          pip uninstall pynwb -y
          pip install pynwb==2.1.0
      - name: Update testing configuration path
        run: python -c "from nwbinspector.testing import update_testing_config; update_testing_config(key='LOCAL_PATH', value='./testing_files/')"
      - name: Generate testing files
        run: python -c "from nwbinspector.testing import generate_testing_files; generate_testing_files()"
      - name: Upload to DANDI
        run: |
          dandi download 'https://gui-staging.dandiarchive.org/#/dandiset/204919' --download dandiset.yaml
          cd 204919
          mv ../testing_files .
          dandi upload -i dandi-staging --validation ignore  # These are purposefully invalid files
